### ISSUE TITLE
where is sql file?

### ISSUE THREAD

**Issue by wisnubaldas** [luchothoma/ci3-app-web#1]
hi, im try to clone, but error and error,

where is database config file? 
database noting? 

tanks,

**Comment by luchothoma** [comment]
Hi there !

Probably I forgot to add in the readme that the SQL needed is only the start one required by Ion Auth depending on your database management system used:

- SqlServer: https://github.com/benedmunds/CodeIgniter-Ion-Auth/blob/3/sql/ion_auth.mssql.sql
- Postgres: https://github.com/benedmunds/CodeIgniter-Ion-Auth/blob/3/sql/ion_auth.postgre.sql
- MySql: https://github.com/benedmunds/CodeIgniter-Ion-Auth/blob/3/sql/ion_auth.sql

For all of them the default login user is: email-> admin@admin.com | password-> password
